<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

<!--    <script src='js/passwordRandom.js' defer></script>-->
<!--    <script src='js/registerUser.js' defer></script>-->
<!--    <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>-->
<!--    <link rel="stylesheet" href="css/admin.css">-->

    <title>AcademyPortal | Register Applicant</title>
</head>
<body>
<div>
    <a href="/admin" class="returnButton">Return to admin page</a>
</div>
<h1> Applicant Registration Page</h1>
<div id="message"></div>
<form id="registerApplicantForm">
    <div>
        <h4>Name</h4>
        <input type="text">
    </div>
    <div>
        <h4>Email</h4>
        <input id="emailNewApplicant" type="email" name="email">
    </div>
    <div>
        <h4>COHORT APPLYING FOR</h4>
        <select name="cohort" id="cohort">
            <option value="feb2019">11 February 2019</option>
            <option value="aug2019">27 August 2019</option>
            <option value="feb2020">10 February 2020</option>
            <option value="aug2020">25 August 2020</option>
        </select>
        <input type="submit" id="newApplicantSubmit">
    </div>
</form>
</body>
</html>